# ==============================================================================
# RESOURCES THAT FULLY SUPPORT GCP LABELS (100% Implemented)
# ==============================================================================
SUPPORTED_LABEL_RESOURCES = {
    # "aiplatform.googleapis.com/Dataset",
    # "aiplatform.googleapis.com/Model",
    # "alloydb.googleapis.com/Cluster",
    # "alloydb.googleapis.com/Instance",
    # "appengine.googleapis.com/Application",
    # "appengine.googleapis.com/Version",
    # "artifactregistry.googleapis.com/Repository",
    # "bigquery.googleapis.com/Dataset",
    # "bigquery.googleapis.com/Table",
    # "bigquery.googleapis.com/Model",
    # "cloudfunctions.googleapis.com/CloudFunction",
    # "cloudfunctions.googleapis.com/Function",
    # "cloudkms.googleapis.com/CryptoKey",
    "cloudresourcemanager.googleapis.com/Project",
    # "compute.googleapis.com/Address",
    # "compute.googleapis.com/Disk",
    # "compute.googleapis.com/ForwardingRule",
    # "compute.googleapis.com/Image",
    # "compute.googleapis.com/Instance",
    # "compute.googleapis.com/MachineImage",
    # "compute.googleapis.com/Snapshot",
    # "compute.googleapis.com/BackendService",
    # "compute.googleapis.com/HealthCheck",
    # "compute.googleapis.com/SslCertificate",
    # "compute.googleapis.com/TargetHttpProxy",
    # "compute.googleapis.com/TargetHttpsProxy",
    # "compute.googleapis.com/UrlMap",
    # "container.googleapis.com/Cluster",
    # "dataform.googleapis.com/Repository",
    # "dataplex.googleapis.com/DataScan",
    # "dataplex.googleapis.com/EntryGroup",
    # "dns.googleapis.com/ManagedZone",
    # "monitoring.googleapis.com/AlertPolicy",
    # "pubsub.googleapis.com/Subscription",
    # "pubsub.googleapis.com/Topic",
    # "redis.googleapis.com/Instance",
    # "run.googleapis.com/Service",
    # "secretmanager.googleapis.com/Secret",
    # "sqladmin.googleapis.com/Instance",
    # "storage.googleapis.com/Bucket",
}

# ==============================================================================
# RESOURCES THAT ONLY SUPPORT GCP TAGS (Safely Bypassed for Now)
# ==============================================================================
SUPPORTED_TAG_RESOURCES = {
    # "compute.googleapis.com/ExternalVpnGateway",
    # "compute.googleapis.com/Firewall",
    # "compute.googleapis.com/Network",
    # "compute.googleapis.com/Route",
    # "compute.googleapis.com/Router",
    # "compute.googleapis.com/Subnetwork",
    # "compute.googleapis.com/TargetPool",
    # "compute.googleapis.com/TargetVpnGateway",
    # "compute.googleapis.com/VpnGateway",
    # "compute.googleapis.com/VpnTunnel",
}
