SUPPORTED_LABEL_RESOURCES = {
    "compute.googleapis.com/Subnetwork",
    "compute.googleapis.com/HealthCheck",
    "compute.googleapis.com/NetworkEndpointGroup",
    "compute.googleapis.com/BackendService",
    "compute.googleapis.com/Disk",
    "compute.googleapis.com/Firewall",
    "compute.googleapis.com/ForwardingRule",
    "compute.googleapis.com/Address",
    "compute.googleapis.com/Instance",
    "compute.googleapis.com/SslCertificate",
    "compute.googleapis.com/TargetHttpsProxy",
    "compute.googleapis.com/UrlMap",
    "compute.googleapis.com/Snapshot",
    "compute.googleapis.com/Network",
    "compute.googleapis.com/TargetHttpProxy",
    "compute.googleapis.com/MachineImage",
    "compute.googleapis.com/InstanceGroup",
    "compute.googleapis.com/InstanceTemplate",
    "compute.googleapis.com/InstanceGroupManager",
    "compute.googleapis.com/SslPolicy",
    "compute.googleapis.com/Router",
    "compute.googleapis.com/Image",
    "compute.googleapis.com/VpnTunnel",
    "compute.googleapis.com/TargetPool",
    "compute.googleapis.com/HttpHealthCheck",
    "compute.googleapis.com/ResourcePolicy",
    "compute.googleapis.com/TargetVpnGateway",
    "compute.googleapis.com/NetworkAttachment",
    "compute.googleapis.com/SecurityPolicy",
    "compute.googleapis.com/ServiceAttachment",
    "compute.googleapis.com/VpnGateway",
    "compute.googleapis.com/PacketMirroring",
    "compute.googleapis.com/ExternalVpnGateway",
    # "storage.googleapis.com/Bucket",
    # "bigquery.googleapis.com/Dataset",
    # "sqladmin.googleapis.com/Instance",
    # "artifactregistry.googleapis.com/Repository",
    #"pubsub.googleapis.com/Topic",
    # "container.googleapis.com/Cluster",
    # "container.googleapis.com/NodePool",
    # "secretmanager.googleapis.com/Secret",
    # "cloudresourcemanager.googleapis.com/Project",
    # "cloudkms.googleapis.com/CryptoKey",
    # "apikeys.googleapis.com/Key",
    # "appengine.googleapis.com/Application",
    # "appengine.googleapis.com/Service",
    # "appengine.googleapis.com/Version",
    # "cloudfunctions.googleapis.com/Function",
}

SUPPORTED_TAG_RESOURCES = {
    # Populate only with officially supported
    # resource types after verification.
    # "pubsub.googleapis.com/Topic",
    # "compute.googleapis.com/ForwardingRule",
}